### ISSUE TITLE
Allow replacing the files

### ISSUE THREAD

**Issue by LiEnby** [PMStanley/PSV-Exporter#1]
https://www.youtube.com/watch?v=ltid-Gjd3-k the CBPS team just cracked the PSV signature generation . . .

editing PSV files wen eta ?
https://github.com/dots-tb/ps3-psvresigner/blob/1.0/src/main.c

**Comment by PMStanley** [comment]
Thanks for letting me know! I'll dig out an old VM to see if I still have the tools I used to build PSV exporter back in 2007 still available, if not I'll see what options there are for rebuilding in a different language/platform.

**Comment by PMStanley** [comment]
I’ve updated PSV Exporter to import .max saves (PS2) and .mcs (PS1) and export to PSV, .max and .mcs

Only issue is my webhost had issues on Friday which are ongoing and I don’t expect to be resolved until Monday at the earliest. I’ve moved the site to a new host but The DNS update will take 24/48 hours. 

Once I’ve been able to upload the new exe to the main site I’ll close this issue. Source will updated in a week or 2 when I’ve had chance to clean it up a bit (had to make some major changes to accommodate the new features)

**Comment by PMStanley** [comment]
The update has [been released](https://www.ps2savetools.com/2019/08/11/psv-exporter-1-3-released-with-full-psv-support/)

**Comment by bucanero** [comment]
hello @PMStanley @KuromeSan 

Based on `ps3-psvresigner` and code from PSV Exporter (and others), I made a simple command line tool to convert and resign PS1 and PS2 savegames to the PS3 PSV format. It works on macOS, Linux and Windows:
https://github.com/bucanero/psv-save-converter

Thanks for sharing your sources and tools 👍
