### ISSUE TITLE
Batch mode?

### ISSUE THREAD

**Issue by IngwiePhoenix** [PMStanley/PSV-Exporter#2]
Hello!

I have just copied just about every save file I have from my old memory cards and I would like to extract them in batch since they are quite a lot of them. Both PS2 and PS1.

My goal:
- Extract PS1 as .mcr so it can be imported using PSXGE.
- Extract PS2 as `$gameId` folder, which can be used by PCSX2 for loading.

I wasn't able to find a command line usage yet which I could utilize for batch processing.

Have a great day and kind regards,
Ingwie

**Comment by PMStanley** [comment]
Hi Ingwie, there's no command line implementation and I'm not actively working on this project at this time.   I suggesting looking at something like [AutoIt](https://www.autoitscript.com/site/) to enable you to batch process the files without needing any changes to PSV Exporter.
